---

- name: Create the application user
  user: name={{ application_user }} state=present

- name: Create the application group
  group: name={{ application_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ application_user }} group={{ application_group }} state=present

- name: Create the application folders
  become: yes
  become_user: "{{ application_user }}"
  file: path={{ item }}
        owner={{ application_user }}
        group={{ application_group }}
        mode=0775
        state=directory
  with_items:
    - "{{ application_bin_path }}"
    - "{{ application_log_path }}"
    - "{{ application_run_path }}"
    - "{{ application_source_path }}"
    - "{{ application_www_path }}"
    - "{{ application_www_path }}/static"
    - "{{ application_www_path }}/media"
    - "{{ application_config_path }}"
    - "{{ application_config_path }}/ssl"

